### ISSUE TITLE
Put New Links Instead Of Old Ones

### ISSUE THREAD

**Issue by Akashsri3bi** [narayan954/Acadmica#10]
Change Links Of Discord And Others With Links Of Your Websites Or Youtube Videos Or GDSC NIET Social Media

**Comment by rehan985** [comment]
Hi, can you provide the specific links or do I have to put the random links?

**Comment by Edema-wxd** [comment]
Hey, is this issue still open and can you provide the links?

**Comment by narayan954** [comment]
hello there, this issue was part of a closed event and has finished, so Im closing this. Thanks for your interest
