### ISSUE TITLE
FAQ section on homepage

### ISSUE THREAD

**Issue by Edema-wxd** [narayan954/Acadmica#113]
Text color doesn't revert back after closing accordion menu
![Screenshot 2023-03-25 094400](https://user-images.githubusercontent.com/100766884/227707164-91f0ed65-dd0f-42f5-8df9-5b159f8dcded.png)

@narayan954 can i work on this?

**Comment by narayan954** [comment]
Sure you can :), go ahead!

**Comment by Edema-wxd** [comment]
i have fixed it, here is the link to my PR [link](https://github.com/narayan954/Acadmica/pull/114)
