### ISSUE TITLE
bug in studyroom.html

### ISSUE THREAD

**Issue by narayan954** [narayan954/Acadmica#12]
"MAKAUT based UnderGrad" => is not in center of that div. We have to create sepearte div for it and make it center using this :
display: flex;
justify-content: center;
text-align: center;

**Comment by Devam433** [comment]
I want to work in this issue

**Comment by Muhammad-Awab** [comment]
I would like to work on this project. Please assign to me.

**Comment by narayan954** [comment]
> I would like to work on this project. Please assign to me.

please contribute in the original repo now [here](https://github.com/tier3guy/Acadmica)
